### ISSUE TITLE
As a user I want to search for direct ticket numbers (including project abbreviations)

### ISSUE THREAD

**Issue by JimTim** [web-pal/chronos-timetracker#54]
## Expected Behavior
As a user I want to search for direct ticket numbers (including project abbreviations)

## Actual Behavior
doesn't yet work like this

## Steps to Reproduce the Problem

  1. open search and search for ticket numbers

## Specifications

  - Chronos-timetracker version: 2.4.6
  - OS: MacOS

**Comment by Architektor** [comment]
You can search by direct ticket numbers but you need to enter just a number, without the project abbreviation. This is due to Jira search technical limitations. See screenshot.
<img width="435" alt="chronos 2" src="https://user-images.githubusercontent.com/4680555/35387918-5ccedf84-01da-11e8-98d9-de0b3fa172fc.png">

**Comment by VladimirPal** [comment]
Done(development branch). Will be in the next release.

**Comment by JimTim** [comment]
working, THX!
