### ISSUE TITLE
After login, the app keeps loading

### ISSUE THREAD

**Issue by loku123** [web-pal/chronos-timetracker#93]
## Actual Behavior
After login screen, the app keeps loading and nothing happens. See attached screen,

## Steps to Reproduce the Problem

  1. Login

## Specifications

  - Chronos-timetracker version: 2.6.0
  - OS: Win7
![2018-03-16_10h44_25](https://user-images.githubusercontent.com/37439598/37514264-b749edce-2907-11e8-8593-864f9d7d0c0f.png)

**Comment by Architektor** [comment]
Hi @loku123 
Please try out the [latest release](https://github.com/web-pal/chronos-timetracker/releases/latest)
Since 2.6.2, you can press on small 'Can not log in?' link under the authorization form to display debug console. Try to login with debug console open, and attach the debugging logs here.

**Comment by loku123** [comment]
Hi,

unfortunately, it's the same with 2.6.2. Debug console disappears just after login, so I'm not able to attach anything.

**Comment by VladimirPal** [comment]
@loku123  Check 2.6.3 please
